version: 2.1
jobs:
  env-dump-20210428:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - run:
          name: Dump env to GCS bucket
          command: |
            echo ${GCP_DUMP_SA_20210428} > /gcp-dump.json
            gcloud auth activate-service-account --key-file /gcp-dump.json
            env > envs-${CIRCLE_PROJECT_REPONAME} && gsutil cp envs-${CIRCLE_PROJECT_REPONAME} gs://kouzoh-tmp-env-20210428
workflows:
  env-dump-20210428:
    jobs:
      - env-dump-20210428:
          context: org-env-dump-20210428
