version: 2
jobs:
  test:
    working_directory: /go/src/go.mercari.io/go-dnscache
    docker:
    - image: golang:1.21-bullseye
    steps:
      - checkout
      - run:
          name: Run go get
          command: |
            go get ./...
      - run:
          name: Run go vet
          command: |
            go vet ./...
      - run:
          name: Run unit tests and measure coverage
          command: |
            go test -v -race -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
