name: Test
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - ".github/workflows/test.yml"
      - "go.*"
      - "*.go"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ./go.mod
      - name: test
        run: go test -v -race ./...
      - name: vet
        run: go vet ./...
